import type { Node } from 'vis-network'

export interface ProjectNode extends Partial<Node> {
  name: string
  display?: string
  link: string
  color?: string
  dashed?: boolean
  from?: string[]
  deps?: string[]
}

export const projects: ProjectNode[] = [
  {
    name: 'breadsplit',
    display: 'BreakSplit',
    link: 'https://github.com/breadsplit/breadsplit',
    color: '#555',
    x: 0,
    y: 0,
  },
  {
    name: 'i18n-ally',
    display: 'i18n Ally',
    link: 'https://github.com/lokalise/i18n-ally',
    color: '#351',
    from: ['breadsplit'],
  },
  {
    name: 'vueuse',
    display: 'VueUse',
    link: 'https://github.com/vueuse/vueuse',
    from: ['breadsplit'],
    shape: 'circle',
    color: '#42b883',
  },
  {
    name: '@vue/composition-api',
    link: 'https://github.com/vuejs/composition-api',
    color: '#42b883',
    dashed: true,
    from: ['vueuse'],
  },
  {
    name: 'vue-demi',
    display: 'VueDemi',
    link: 'https://github.com/vueuse/vue-demi',
    color: '#42b883',
    from: ['vueuse', '@vue/composition-api'],
  },
  {
    name: 'vue',
    display: 'Vue 3',
    link: 'https://github.com/vuejs/core',
    color: '#42b883',
    dashed: true,
    from: ['@vue/composition-api'],
  },
  {
    name: 'vite',
    display: 'Vite',
    link: 'https://github.com/vitejs/vite',
    color: '#454ce1',
    dashed: true,
    from: ['vue'],
  },
  {
    name: 'icones',
    display: 'Icones',
    link: 'https://github.com/antfu/icones',
    color: '#834',
    shape: 'circle',
    from: ['vite', 'vue'],
  },
  {
    name: 'unplugin-icons',
    link: 'https://github.com/unplugin/unplugin-icons',
    color: '#525',
    from: ['icones'],
  },
  {
    name: 'iconify',
    display: 'Iconify',
    link: 'https://iconify.design/',
    color: '#814',
    dashed: true,
    from: ['unplugin-icons'],
  },
  {
    name: 'Iconify IntelliSense',
    link: 'https://github.com/antfu/vscode-iconify',
    color: '#814',
    from: ['iconify'],
  },
  {
    name: 'unplugin-vue-components',
    link: 'https://github.com/unplugin/unplugin-vue-components',
    color: '#525',
    from: ['icones'],
  },
  {
    name: 'unplugin-auto-import',
    link: 'https://github.com/unplugin/unplugin-auto-import',
    color: '#525',
    from: ['icones'],
  },
  {
    name: 'vite-pwa',
    link: 'https://github.com/vite-pwa',
    color: '#750',
    from: ['icones'],
  },
  {
    name: 'vite-plugin-inspect',
    link: 'https://github.com/antfu-collective/vite-plugin-inspect',
    color: '#454ce1',
    from: ['unplugin-vue-components'],
  },
  {
    name: 'vitesse',
    display: 'Vitesse',
    shape: 'circle',
    link: 'https://github.com/antfu/vitesse',
    color: '#895',
    from: ['icones', 'unplugin-vue-components', 'unplugin-auto-import', 'vite-pwa', 'unplugin-icons'],
    deps: ['vueuse'],
  },
  {
    name: 'vitesse-webext',
    link: 'https://github.com/antfu/vitesse-webext',
    color: '#895',
    from: ['vitesse'],
  },
  {
    name: 'webext-bridge',
    link: 'https://github.com/serversideup/webext-bridge',
    color: '#405',
    from: ['vitesse-webext'],
  },
  {
    name: 'vitesse-nuxt3',
    link: 'https://github.com/antfu/vitesse-nuxt3',
    color: '#895',
    from: ['vitesse'],
  },
  {
    name: 'vitesse-theme',
    link: 'https://github.com/antfu/vscode-theme-vitesse',
    color: '#895',
    from: ['vitesse', 'vueuse'],
  },
  {
    name: 'antfu.me',
    link: 'https://antfu.me',
    color: '#459',
    from: ['vitesse'],
  },
  {
    name: 'vite-ssg',
    link: 'https://github.com/antfu/vite-ssg',
    color: '#459',
    from: ['antfu.me'],
    deps: ['vitesse'],
  },
  {
    name: 'windicss',
    display: 'Windi CSS',
    link: 'https://github.com/windicss/windicss',
    color: '#09f',
    dashed: true,
    from: ['vitesse'],
  },
  {
    name: 'slidev',
    display: 'Slidev',
    link: 'https://github.com/slidevjs/slidev',
    color: '#2ae',
    shape: 'circle',
    from: ['vitesse'],
    deps: ['windicss', 'vueuse'],
  },
  {
    name: 'broz',
    link: 'https://github.com/antfu/broz',
    color: '#2ae',
    from: ['slidev'],
  },
  {
    name: 'drauu',
    link: 'https://github.com/antfu/drauu',
    color: '#2ae',
    from: ['slidev'],
  },
  {
    name: 'unocss',
    display: 'UnoCSS',
    link: 'https://github.com/unocss/unocss',
    color: '#123',
    from: ['slidev', 'windicss'],
    deps: ['vitesse'],
  },
  {
    name: 'nuxt',
    display: 'Nuxt',
    link: 'https://github.com/nuxt/nuxt',
    dashed: true,
    color: '#00c58e',
    from: ['vitesse'],
  },
  {
    name: 'unplugin',
    display: 'Unplugin',
    link: 'https://github.com/unjs/unplugin',
    color: '#525',
    from: ['nuxt'],
    deps: ['unplugin-icons', 'unplugin-auto-import', 'unplugin-vue-components'],
  },
  {
    name: 'vite-node',
    link: 'https://github.com/vitest-dev/vitest/tree/main/packages/vite-node',
    color: '#982',
    from: ['nuxt', 'vite'],
  },
  {
    name: 'vitest',
    display: 'Vitest',
    shape: 'circle',
    link: 'https://github.com/vitest-dev/vitest',
    color: '#982',
    from: ['vite', 'vite-node'],
  },
  {
    name: 'birpc',
    link: 'https://github.com/antfu/birpc',
    color: '#982',
    from: ['vitest'],
  },
  {
    name: 'nuxt-devtools',
    display: 'Nuxt DevTools',
    link: 'https://github.com/nuxt/devtools',
    color: '#00c58e',
    from: ['nuxt', 'vite-plugin-inspect'],
    deps: ['birpc'],
  },
  {
    name: 'learn.nuxt.com',
    link: 'https://github.com/nuxt/learn.nuxt.com',
    color: '#00c58e',
    from: ['nuxt'],
  },

  {
    name: 'shiki',
    display: 'Shiki',
    link: 'https://github.com/shikijs/shiki',
    dashed: true,
    color: '#055',
    from: ['nuxt', 'antfu.me', 'slidev'],
  },
  {
    name: 'shiki-magic-move',
    link: 'https://github.com/shikijs/shiki-magic-move',
    color: '#055',
    from: ['shiki', 'slidev'],
  },
  {
    name: 'shiki/monaco',
    link: 'https://github.com/shikijs/shiki',
    color: '#055',
    from: ['learn.nuxt.com', 'shiki'],
  },
  {
    name: 'twoslash',
    display: 'Twoslash',
    link: 'https://github.com/twoslashes/twoslash',
    color: '#055',
    dashed: true,
    from: ['shiki'],
  },
  {
    name: '@antfu/eslint-config',
    link: 'https://github.com/antfu/eslint-config',
    color: '#53f',
  },
  {
    name: '@eslint/config-inspector',
    link: 'https://github.com/eslint/config-inspector',
    color: '#53f',
    from: ['@antfu/eslint-config'],
    deps: ['nuxt-devtools'],
  },
  {
    name: 'eslint-flat-config-utils',
    link: 'https://github.com/antfu/eslint-flat-config-utils',
    color: '#53f',
    from: ['@antfu/eslint-config'],
  },
  {
    name: 'eslint-typegen',
    link: 'https://github.com/antfu/eslint-typegen',
    color: '#53f',
    from: ['@antfu/eslint-config'],
  },
  {
    name: '@nuxt/eslint',
    display: 'Nuxt ESLint',
    link: 'https://github.com/nuxt/eslint',
    color: '#00c58e',
    from: ['@antfu/eslint-config', 'nuxt'],
  },
  {
    name: 'eslint-stylistic',
    display: 'ESLint Stylistic',
    link: 'https://github.com/eslint-stylistic/eslint-stylistic',
    color: '#59f',
    from: ['@antfu/eslint-config'],
  },
]
